

spring:
  datasource:
    username: dservice
    password: tjqltm!!@
    url: jdbc:mysql://10.202.19.216:3306/tools_bsc_job_kakaom?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id: false
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      fail-on-empty-beans: false

  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
